//------------------------------------------------------------------------
// Copyright(c) 2023 Plexus Harmony.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"HarmoniPlex200.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"HarmoniPlex200 VST3 (64Bit)"
#else
#define stringFileDescription	"HarmoniPlex200 VST3"
#endif
#define stringCompanyName		"Plexus Harmony\0"
#define stringLegalCopyright	"Copyright(c) 2023 Plexus Harmony."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
